apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/hyperledger-labs/fabric-operator.git/config/crd
  - https://github.com/hyperledger-labs/fabric-operator.git/config/ingress/kind
  - https://github.com/hyperledger-labs/fabric-operator.git/sample-network/config/manager
  - https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml
  - sail-role.yaml
  - sail-rolebinding.yaml
