apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: series

  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]


  - name: sequence
    steps:
      - - name: hello
          inline:
            container:
              image: docker/whalesay:latest
              command: [cowsay]
              args: ["hello"]


      - - name: world
          inline:
            container:
              image: docker/whalesay:latest
              command: [cowsay]
              args: ["world"]


  - name: series
    steps:
      - - name: doit
          inline:
            steps:
              - - name: a
                  inline:
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["AAA"]

              - - name: b
                  inline:
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["BBB"]
