apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: network-up
  templates:
    - name: network-up
      steps:
        - - name: hello
            inline:
              container:
                image: docker/whalesay:latest
                command: [cowsay]
                args: ["ahoy"]

        - - name: world
            inline:
              container:
                image: docker/whalesay:latest
                command: [cowsay]
                args: ["world"]
